from enum import Enum


class Type(Enum):
    SPACE = "( ).*"
    OPEN_PAREN = "(\\().*"
    CLOSE_PAREN = "(\\)).*"
    SEMICOLON = "(;).*"
    OPEN_CURLY_BRACE = "(\\{).*"
    CLOSE_CURLY_BRACE = "(\\}).*"
    OPEN_BRACE = "(\\[).*"
    CLOSE_BRACE = "(\\]).*"
    DOUBLE_CONSTANT = "\\b(\\d{1,9}\\.\\d{1,32})\\b.*"
    INT_CONSTANT = "\\b(\\d{1,9})\\b.*"
    VOID = "\\b(void)\\b.*"
    INT = "\\b(int)\\b.*"
    DOUBLE = "\\b(int|double)\\b.*"
    TAB = "(\\t).*"
    NEW_LINE = "(\\n).*"
    PUBLIC = "\\b(public)\\b.*"
    PRIVATE = "\\b(private)\\b.*"
    FALSE = "\\b(false)\\b.*"
    TRUE = "\\b(true)\\b.*"
    NULL = "\\b(null)\\b.*"
    RETURN = "\\b(return)\\b.*"
    NEW = "\\b(new)\\b.*"
    CLASS = "\\b(class)\\b.*"
    IF = "\\b(if)\\b.*"
    ELSE = "\\b(else)\\b.*"
    WHILE = "\\b(while)\\b.*"
    STATIC = "\\b(static)\\b.*"
    STRING = "\\b(String)\\b.*"
    CHAR = "\\b(char)\\b.*"
    CONTINUE = "\\b(continue)\\b.*"
    BOOLEAN = "\\b(boolean)\\b.*"
    BREAK = "\\b(break)\\b.*"
    ENUM = "\\b(enum)\\b.*"
    FLOAT = "\\b(float)\\b.*"
    POINT = "(\\.).*"
    PLUS = "(\\+{1}).*"
    MINUS = "(\\-{1}).*"
    MULTIPLY = "(\\*).*"
    DIVIDE = "(/).*"
    EQUAL = "(==).*"
    ASSIGNMENT = "(=).*"
    NOT_EQUAL = "(\\!=).*"
    CLOSE_CARET = "(>).*"
    OPEN_CARET = "(<).*"
    IDENTIFIER = "\\b([a-zA-Z]{1}[0-9a-zA-Z_]{0,31})\\b.*"
    STRING_LITERAL = '\"(\\.|[^\\"])*\"'
    CHARACTER_LITERAL = r"\'(\\.|[^\\'])*\'"